; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$TTL    55	
@	IN	SOA	kitchenseeker.com. root.kitchenseeker.com. (
			      1		; Serial
			 604800		; Refresh
			  86400		; Retry
			2419200		; Expire
			  86400 )	; Negative Cache TTL
;
@	IN	NS	ns.kitchenseeker.com.
ns	IN 	A	10.240.69.241;
mysql   IN	A	10.240.37.202;
